#!/bin/bash

sqlfile=".dbcmp.sql"
tmpfile=".dbcmp.tmp"

source dbcmp.cfg

function gendiffsql()
{
    tabdef=$1
    tab=$2;
    condstr=$3

    tab_name1=${prefix1}${tab}${suffix1};
    tab_name2=${prefix2}${tab}${suffix2};
    tab=${tab%_*};
    count=0;
    cols=;
    cols2=;
    colnames=;

    while read col
    do
        if [ -z "$col" ]; then
            continue;
        fi
        col2=$col;

        count=`expr $count + 1`;
        if [ $count -ge '15' ]; then
            cols="$cols\n"
            cols2="$cols2\n"
            colnames="$colnames\n"
            count=0;
        fi
            
        #exclude cols
        exclude_str=`grep "^__GLOBAL__:.*|$col|" "$xcols_path$xcols_file"`;
        if [ -n "$exclude_str" ]; then
            continue;
        else
            exclude_str=`grep "^$tab:.*|$col|" "$xcols_path$xcols_file"`;
        fi

        if [ -n "$exclude_str" ]; then
            tmp=${exclude_str#*|$col|};
            if [ "${tmp:0:7}" == 'UPDATE;' ]; then
                tmp=${tmp:7};
                col="${tmp%%;*} \"$col\"";
            else 
                continue;
            fi
        fi
        cols="$cols,$col";
        cols2="$cols2,'''',$col2,''','";
        colnames="$colnames,'''','$col2',''','";
    done <$tabdef


    cols="${cols:1}";
    cols2="${cols2:1}";
    cols2="'[',${cols2},'],'";
    colnames="${colnames:1}";
    colnames="'[',${colnames},'],'";

    if [ -n "$maxrownum" ]; then
        rownumcntl="where rownum <= $maxrownum";
    fi

    echo -e "set termout on" >>$sqlfile;
    echo -e "select '//Comparing $tab ', to_char(sysdate,'hh24:mi:ss') from dual;" >>$sqlfile;
    echo -e "set termout off" >>$sqlfile;
    echo -e "prompt var $tab_name1 = new Array( " >>$sqlfile;
    echo -e "select $colnames from dual;" >>$sqlfile;
    echo -e "select $cols2 from " >>$sqlfile;
    echo -e "(select $cols from $prefix1${tab}$suffix1 $condstr minus" >>$sqlfile;
    echo -e " select $cols from $prefix2${tab}$suffix2 $condstr) $rownumcntl;">>$sqlfile;
    echo -e "prompt [])"  >>$sqlfile;
    echo -e "prompt var $tab_name2 = new Array( " >>$sqlfile;
    echo -e "select $colnames from dual;" >>$sqlfile;
    echo -e "select $cols2 from " >>$sqlfile;
    echo -e "(select $cols from $prefix2${tab}$suffix2 $condstr minus" >>$sqlfile;
    echo -e " select $cols from $prefix1${tab}$suffix1 $condstr) $rownumcntl;">>$sqlfile;
    echo -e "prompt [])"  >>$sqlfile;
    echo -e "-------------------">>$sqlfile;
}

function initsql() 
{
  echo "data initialization begun."
  echo "define variables=${sqlvarlist//;/||}" >$sqlfile
  echo "spool $rptfile append" >>$sqlfile
  echo "set heading off" >>$sqlfile
  echo "set feedback off" >>$sqlfile
  echo "set ver off" >>$sqlfile
  echo "set line 20000" >>$sqlfile
  echo "set termout off" >>$sqlfile
  echo "set trimspool on" >>$sqlfile
  echo "WHENEVER OSERROR EXIT FAILURE" >>$sqlfile
  echo "WHENEVER SQLERROR EXIT FAILURE" >>$sqlfile

  while read tab condstr
  do
    tab=${tab%%#*};
    condstr=${condstr%%#*};
    if [ -z "$tab" ]; then
      continue;
    fi
    
    if [ -z "$condstr" ]; then
      condstr=$default_condstr;
    fi
    
    echo .$tab,$condstr;
    
    result=`
sqlplus -S $db_user/$db_passwd@$db_inst <<EOF
set heading off 
set feedback off 
set ver off
spool $tmpfile
set trimspool on
define tbl1=$prefix1${tab%_*}$suffix1;
define tbl2=$prefix2${tab%_*}$suffix2;
select COLUMN_NAME from COLS where TABLE_NAME =upper('&tbl1') intersect select COLUMN_NAME from COLS where TABLE_NAME =upper('&tbl2');
quit;
EOF
`

    errinf=`echo $result|grep "ERROR:"`;
    if [ -n "$errinf" ]; then
        echo "data initialization error"
        echo $errinf;
        exit 1;
    fi
    
    gendiffsql $tmpfile $tab "$condstr"
      
  done <$tablist
  echo "quit;" >>$sqlfile
  echo "data initialization finished, execute 'dbcmp run' command to compare. "
}

function runCmp()
{
  echo "data compare begun"
  cat >$rptfile <<EOF
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=gb2312">
</head>
<body>
    <script>
            /* data elements */
EOF
  sqlplus -S $db_user/$db_passwd@$db_inst @$sqlfile
  if [ "$?" != "0" ]; then 
    echo "data compare error"
    tail -n 10 $rptfile;
    exit;
  fi
  cat >>$rptfile<<EOF
    </script>
    <div id="mydiv">
    <h2 align="center"> Data Compare Report </h2>
      <script>
EOF
  for tab in `cat $tablist |grep -v "^ *\#" |awk '{print $1}'`
  do
    echo "if($prefix1$tab$suffix1.length<=2 && $prefix2$tab$suffix2.length<=2 ){" >>$rptfile
    echo "  document.write('Table ${tab} has no difference. <br>');" >>$rptfile
    echo "} else {" >>$rptfile
    echo "  document.write('Table ${tab} has some differences: <a href=\"javascript:print($prefix1$tab$suffix1,$prefix2$tab$suffix2,\'$prefix1$tab$suffix1\', \'$prefix2$tab$suffix2\')\"> view detail  </a> <br>');" >>$rptfile
    echo "}"  >>$rptfile
  done

  if [ -n "$maxrownum" ]; then
    echo "var maxrownum=$maxrownum" >>$rptfile;
  fi

  cat >>$rptfile<<EOF
      </script>
    </div>
    <div id="help">
    </div>
</body>
</html>

<script>
var PointX=0;PointY=0;
function ChangeValue(tname,i,j,value2) {
    var x=document.getElementById(tname).rows[i].cells;
    x[j+1].innerHTML=value2;
}
function savePoint() {    
    ev=window.event;
    if(typeof(ev)!='undefined'){
        PointX=ev.x;
        PointY=ev.y;
    }
}

function ChangeValues(table1, table2, tname1, tname2) {
    ev=window.event;
    if(typeof(ev)!='undefined'){
        if(ev.x!=PointX || ev.y != PointY) {
            return;
        }
    }
    reprint(table2, table1, tname2, tname1);
}
function SortAsc(table1,table2,tname1,tname2,col) {
    var r=confirm("Sort this column ascending?");
    if (r==true) {
        var head1=table1.shift();
        var head2=table2.shift();
        table1.sort( function(x,y) {
            return (x[col].localeCompare(y[col]))
        });
        table2.sort( function(x,y) {
            return (x[col].localeCompare(y[col]))
        });
        table1.unshift(head1);
        table2.unshift(head2);
        reprint(table1, table2, tname1, tname2);
    }
}
function MoveBtn(table1,table2,tname1,tname2,i) {
    var r=confirm("Move this record to bottom?");
    if (r==true) {
        var rec=table1.splice(i,1);
        table1.push(rec[0]);
        reprint(table1, table2, tname1, tname2);
    } 
}

function showHelp() {
    var helptext;
    helptext="<br>> Red cells means difference, view another value by move mouse over. <br>";
    helptext+="> By click anywhere of the table, you can shift between two tables globally. <br>";
    helptext+="> Move the record by click record's Number left, Sort by click column name. <br>";
    helptext+="> There are some problems when single quote(') appeared, check it manually.<br>";
    helptext+="<br> Open Source Software under GPLV3 licence.<br>";
    helptext+="Websit: http://code.google.com/p/transpring/source/browse/tools/dbcmp <br>";
    helptext+="<br>Contributors:<br>";
    helptext+="V1.1.0  20130816    leiminghuan@126.com    create<br>";
    helptext+="V2.0.1  20130823    leiminghuan@126.com    sorting, record moving, UI optimize<br>";
    helptext+="V2.2.0  20130903    leiminghuan@126.com    column's function, assigned table compare.<br>";
    var stat=document.getElementById("help");
    if(stat.innerHTML == "") {
        stat.innerHTML=helptext;
    }else {
        stat.innerHTML="";
    }
}
function print(table1, table2, tname1, tname2) {
    table1.pop();
    table2.pop();
    reprint(table1, table2, tname1, tname2);
}

function reprint(table1, table2, tname1, tname2) {
    var divtext, RecTmp1, RecTmp2;
    divtext='<a href = "javascript:location.reload()">Home</a>';
    if(typeof(maxrownum) != 'undefined') {
        if(table1.length >= maxrownum || table2.length >= maxrownum ) {
            divtext+='  <font color="#FF0000">(only shown first '+maxrownum+'records)</font>';
        }
    }
    var    td_attrs="";
    divtext+='<table id="'+tname1+'" border = "1" cellspacing = "0" style="border-collapse:collapse" ';
    divtext+='onmousedown="javascript:savePoint()" ';
    divtext+='onmouseup="javascript:ChangeValues('+tname1+','+tname2+',\''+tname1+'\',\''+tname2+'\')" >';
    for( var i=0; i<Math.max(table1.length,table2.length); i++) {
        if(typeof(table1[i]) == 'undefined') {
            RecTmp1=new Array();
        } else {
            RecTmp1=table1[i];
        }
        if(typeof(table2[i]) == 'undefined') {
            RecTmp2=new Array();
        } else {
            RecTmp2=table2[i];
        }
        divtext+="<tr>";
        for( var j=0; j<table1[0].length; j++) {
            if( j==0 ) {
                if(i == 0) {
                    divtext+='<td bgcolor="#c0c0c0" >'+(tname1+'..........').substring(0,12)+'</td>';
                } else {
                    divtext+='<td bgcolor="#F0F0F0" ';
                    divtext+='onmouseup="javascript:MoveBtn('+tname1+','+tname2+',\''+tname1+'\',\''+tname2+'\','+i+')"> ';
                    divtext+=i+'</td>';
                }
            }
            if(typeof(RecTmp1[j]) == 'undefined') {
                RecTmp1[j]="";
            }
            if(typeof(RecTmp2[j]) == 'undefined') {
                RecTmp2[j]="";
            }

            if(RecTmp1[j]!=RecTmp2[j]) {
                td_attrs='bgcolor="#FFAA00" ';
                if(Math.abs(RecTmp1[j]-RecTmp2[j])<0.1) {
                    td_attrs='bgcolor="#FDE0B3" ';
                }
                td_attrs += 'onmouseover="javascript:ChangeValue(\''+tname1+'\','+i+','+j+',\''+RecTmp2[j]+'\')" '+
                    'onmouseout ="javascript:ChangeValue(\''+tname1+'\','+i+','+j+',\''+RecTmp1[j]+'\')" ';

            }
            
            if(i==0) {
                td_attrs='bgcolor="#F0F0F0" ';
                td_attrs+='onmouseup="javascript:SortAsc('+tname1+','+tname2+',\''+tname1+'\',\''+tname2+'\','+j+')" ';
            }
            
            divtext+="<td "+td_attrs+">"+RecTmp1[j]+"</td>";
            td_attrs="";

        }
        divtext+="</tr>";
    }
    divtext+="</table>";
    divtext+='<br><a href = "javascript:showHelp()">Help</a>';
    document.getElementById("mydiv").innerHTML=divtext;
}
</script>

EOF
  echo "data compare finished, see report file:$rptfile".
}

if [ "$1" == 'init' ]; then
  initsql;
  exit;
fi

if [ "$1" == 'run' ]; then
  runCmp;
  exit;
fi

if [ "$1" == 'table' ] && [ -n "$2" ]; then
  sqlfile=".dbcmp_$2.sql";
  rptfile="${rptfile%.html}_$2.html";
  grep -i "^ *$2" $tablist >".dbcmp_$2.tbl"
  tablist=".dbcmp_$2.tbl";
  initsql;
  runCmp;
  rm -f "$sqlfile" "$tablist" 
  exit;
fi

echo "Usage: dbcmp init|run|{table <tname>}";
echo "       init:  run it when fisrt use or table's structure¡¢configure files is changed";
echo "       run :  excute the comparation";
echo "       table: init and run the comparation only for the table <tname>";

